version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  run-tests:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Test Reporter
          command: |
            wget -O ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
            chmod +x ./cc-test-reporter
      - run:
          name: Report Before Build
          command: ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Run tests coverage
          command: npm run coverage
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_docker_image:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run:
          name: "Build Docker Image Server"
          command: |
            export TAG='0.1.<< pipeline.number >>'
            export IMAGE_NAME=ebind-node-server
            docker build -t $DOCKER_LOGIN/$IMAGE_NAME -t $DOCKER_LOGIN/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push -a $DOCKER_LOGIN/$IMAGE_NAME

workflows:
  build:
    jobs:
      - build
      - run-tests:
          requires:
            - build
      - build_docker_image:
          requires:
            - run-tests
